name: BlockShuffle
version: 1.0-SNAPSHOT
main: tris.blockshuffle.BlockShuffle
api-version: 1.13
commands:
  blockshuffle:
    description: start block shuffle
  vote:
    description: votes
  tnt:
    description: spawn lit tnt
  creeper:
    description: spawn a creeper
  zombie:
    description: spawn a zombie